### ISSUE TITLE
Re: Transparent Navigation Bar

### ISSUE THREAD

**Issue by ld991** [corsicanu/goodlock_dump#2]
Is it possible to change this one annoying behaviour of transparent navigation bar feature? The navigation bar overlaps with the bottom toolbar in apps such as YouTube and web browsers.

Pixel phones, for example, do have transparent navigation but this overlapping issue is not present in them.

**Comment by Pablo12215** [comment]
La verdad es que es muy bueno

**Comment by corsicanu** [comment]
Not a manager issue tho, contact samsung devs via local forums and explain the problems.
